### ISSUE TITLE
Wizja.Tv Premium-Nie Dział 

### ISSUE THREAD

**Issue by Huero23** [CherryKodi/CHERRY#16]
Nie ładuje żadnego kanału od dwóch dni.

**Comment by rafalmar1981** [comment]
potwierdzam coś się porobiło na kompie śmiga aż miło a na kodi lipa

**Comment by rafalmar1981** [comment]
czy da się coś zrobić

**Comment by Huero23** [comment]
@rafalmar1981 Jak długo już tobie nie działa?

**Comment by rafalmar1981** [comment]
Huero23 to dzis 3dien

**Comment by frijerz** [comment]
To ja mam jeszcze lepiej: na laptopie na mTvGuide dziala, a na android box nie działa. Ta sama wersja Kodi, taka sama konfiguracja, haslo. Dziwne.

**Comment by xulek** [comment]
> To ja mam jeszcze lepiej: na laptopie na mTvGuide dziala, a na android box nie działa. Ta sama wersja Kodi, taka sama konfiguracja, haslo. Dziwne.

bo na jednym masz zainstalowaną wtyczkę rtmp input a na drugim nie na 99% (nie powinno jej być dla wizjatv)

**Comment by frijerz** [comment]
Co to  za wtyczka? Nie instalowalem jej, jak ja usunąc/wylączyc?

**Comment by Huero23** [comment]
@frijerz Czy możesz powiedzieć gdzie znalazłeś?

**Comment by frijerz** [comment]
Wejdz w Moje dodatki>Wtyczki strumieniowe>InputStream Adaptive i wyłacz ją (albo usuń). Ona byla potrzebna dla jakiejs innej wtyczki, nie pamietam juz dla ktorej.
