### ISSUE TITLE
Dodajcie script.module.request do resolverurl

### ISSUE THREAD

**Issue by notoco** [CherryKodi/CHERRY#2]
Dodajcie do script.module.resolveurl jako zależność script.module.request
Wasza modyfikacja nadpisuje oryginalny resolver i nie chcą z nią działać wtyczki podpisa i różne inne. Poprawka IMO winna być w waszym repo zrobiona, bo to wy modyfikujecie i łatwiej to załatwić jednym wpisem.
https://github.com/notoco/ffl/tree/master/zips/script.module.resolveurl - tu poprawiona wersja u mnie, i poprawiony addons.xml
``<addon id="script.module.resolveurl" name="ResolveURL" version="6.0.7a" provider-name="jsergio">
<requires>
<import addon="xbmc.python" version="2.1.0" />
<import addon="plugin.video.youtube" optional="true" />
		<import addon="script.module.python.twitch" optional="true" />
		<import addon="script.module.cryptopy" version="1.2.6" optional="true" />
		<import addon="plugin.video.gdrive" optional="true" />
		<import addon="script.module.requests" />
	</requires>
	<extension point="xbmc.python.pluginsource" library="main.py">
          <provides>video</provides>
        </extension>
	<extension point="xbmc.python.module" library="lib" />
	<extension point="xbmc.python.pluginsource" library="lib/default.py" />
	<extension point="xbmc.addon.metadata">
		<platform>all</platform>
		<summary lang="en">Resolve common video host URL's to be playable in XBMC/Kodi.</summary>
		<summary lang="es">Resolver enlaces a videos de sitios populares para poder reproducirlos en XBMC/Kodi.</summary>
		<summary lang="hr">Prilagodi najčešće URL-ove video izvora kako bi radili u XBMC/Kodiju.</summary>
		<description lang="en">Resolve common video host URL's to be playable in XBMC/Kodi, simplify addon development of video plugins requiring multi video hosts.</description>
		<description lang="hr">Prilagodi najčešće URL-ove video izvora kako bi radili u XBMC/Kodiju, pojednostavnjuje razvoj priključaka za video dodatke koji zahtjevaju višestruke video izvore.</description>
	</extension>
</addon>``

**Comment by CherryKodi** [comment]
Dwa dni temu ,był resolver wymieniony na zwykły .

**Comment by CherryKodi** [comment]
W addons.xml było tak czy inaczej wymaganie co do zależności script.module.requests od dwóch dni wiec nikomu bez niego nie powinno się zaktualizować. Ale dodałem wersje 7a z tą zależnością

**Comment by notoco** [comment]
Ale na czystym kodi nie wchodziło... Dzięki za pomoc.
