### ISSUE TITLE
Mozecie dodac ten serwis?

### ISSUE THREAD

**Issue by kacperkwapisz** [CherryKodi/CHERRY#20]
To tak, kilka dni temu podeslal mi kolega link do tego serwisu: https://cdahd.ml i mam pytanko czy mozecie go dodac do waszego repo linkow? Jesli tak bym byl wdzieczny i by mi to uproszczylo ogladanie filmow! Zrobilem skrypt ktory wyciaga te linki filmow wiec tylko dodajcie go gdzie trzeba: _nie dzialal wiec usunalem_

NAJNOWSZY LINK: http://zipfile.cf/m83Ri2Qe

**Comment by xulek** [comment]
Na linku ustawione jest hasło

**Comment by K4P1Official** [comment]
oh, moj blad, juz jest nowy link http://zipfile.cf/BcMzqLZl

**Comment by xulek** [comment]
użyta tam jest jakaś dziwna biblioteka cfcookie masz ją?

**Comment by K4P1Official** [comment]
nie nie mam jej, przerobilem ten plik pod https://cdahd.ml bo inny serwis uzywa tej samej techniki wstawiania filmow. Zostala by ona dodana jesli bym ja mial, albo chociaz ogarnal skad albo co to jest?

**Comment by K4P1Official** [comment]
Poszukam jej jak bede w domu. Wysle odrazu jak ja bede mial. Tak wogole bedzie mozliwosc dodania tego serwisu do FanFilm?

**Comment by xulek** [comment]
Możliwość jest zawsze, wszystko zależy od chęci i czasu :)

**Comment by K4P1Official** [comment]
Poprawilem w calosci skrypt, tutaj link do pobrania: http://zipfile.cf/m83Ri2Qe

**Comment by kacperkwapisz** [comment]
Jakieś nowości? [CDAHD](https://cdahd.ml) jest znane ale nie można oglądać filmów z niej na kodim...
