### ISSUE TITLE
Python object files

### ISSUE THREAD

**Issue by rysson** [CherryKodi/CHERRY#4]
script.module.urlresolver-5.0.14.zip zawiera pliki *.pyo, które wydają się zbędne.
Python i tak je wytworzy raz przy pierwszym uruchomieniu w dodatku dokładnie w wersji sobie pasującej.

Proponuję usunąć w kolejnym buildzie. Np. pakować z opcją `zip -r xxx.zip xxx -x '*.pyo'`

**Comment by CherryKodi** [comment]
Nie używamy go już we wtyczkach, jest tylko po to jakby komuś brakowało zależności. Teraz używamy resolveurl 6.*.*

**Comment by rysson** [comment]
o to wszystko jasne, nie co w nim grzebać.
